-- Create table
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(50),
    SALARY NUMBER
);

-- Insert values
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 20000);
INSERT INTO EMPLOYEE VALUES (102, 'Anu', 30000);
INSERT INTO EMPLOYEE VALUES (103, 'Priya', 25000);
INSERT INTO EMPLOYEE VALUES (104, 'Kumar', 40000);
INSERT INTO EMPLOYEE VALUES (105, 'Divya', 35000);

COMMIT;


-- SUM
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE;


-- AVG
SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE;


-- COUNT
SELECT COUNT(SALARY) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;


-- MAX
SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEE;


-- MIN
SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEE;
