CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(50),
    SALARY NUMBER
);

INSERT INTO EMPLOYEE
VALUES (101, 'Ravi', 20000);

COMMIT;

CREATE OR REPLACE TRIGGER CHECK_SALARY
BEFORE INSERT OR UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
    IF :NEW.SALARY < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Salary cannot be negative');
    END IF;
END;
/

UPDATE EMPLOYEE
SET SALARY = -5000
WHERE EMP_ID = 101;

SELECT * FROM EMPLOYEE;
