-- Create first table
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(50),
    DEPT_ID NUMBER
);

-- Insert values
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 10);
INSERT INTO EMPLOYEE VALUES (102, 'Anu', 20);
INSERT INTO EMPLOYEE VALUES (103, 'Priya', 30);
INSERT INTO EMPLOYEE VALUES (104, 'Kumar', 40);


-- Create second table
CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER,
    DEPT_NAME VARCHAR2(50)
);

-- Insert values
INSERT INTO DEPARTMENT VALUES (10, 'HR');
INSERT INTO DEPARTMENT VALUES (20, 'IT');
INSERT INTO DEPARTMENT VALUES (30, 'Finance');
INSERT INTO DEPARTMENT VALUES (50, 'Sales');

COMMIT;


-- INNER JOIN
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;


-- LEFT JOIN
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;


-- RIGHT JOIN
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
RIGHT JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;


-- FULL OUTER JOIN
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
FULL OUTER JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;
