-- Create table
CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(50),
    SALARY NUMBER,
    DEPT_ID NUMBER
);

-- Insert values
INSERT INTO EMPLOYEE VALUES (101, 'Ravi', 20000, 10);
INSERT INTO EMPLOYEE VALUES (102, 'Anu', 30000, 20);
INSERT INTO EMPLOYEE VALUES (103, 'Priya', 25000, 10);
INSERT INTO EMPLOYEE VALUES (104, 'Kumar', 40000, 20);
INSERT INTO EMPLOYEE VALUES (105, 'Divya', 35000, 30);

COMMIT;


-- Nested Subquery
-- Find employees whose salary is greater than
-- the average salary

SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEE
);
