CREATE TABLE BANK_ACCOUNT (
    ACC_NO INT,
    ACC_NAME VARCHAR(50),
    BALANCE INT
);

INSERT INTO BANK_ACCOUNT
VALUES (102, 'Ravi', 6000);

UPDATE BANK_ACCOUNT
SET BALANCE = 8000
WHERE ACC_NO = 102;

ROLLBACK;
