CREATE TABLE PRODUCT (
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(50),
    PRICE INT,
    QUANTITY INT
);

INSERT INTO PRODUCT
VALUES (101, 'Laptop', 50000, 2);

INSERT INTO PRODUCT
VALUES (102, 'Mouse', 800, 10);

SELECT * FROM PRODUCT;
